#%RAML 1.0 Trait
headers:
  api-key:
    description: Api key for the consumer ID
    type: string
    required: false
    example: "<Your Api key>"
  api-secret:
    description: Api secret for app
    type: string
    required: false
    example: "<your Api secret>"
          
      

  